---
- hosts: all

  tasks:
    - name: List files in current directory
      file:
        path: .
        state: file
      register: files

    - name: Print the list of files
      debug:
        var: files.files
